version: '3.4'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_demo
    ports:
      - "5401:5432"
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    networks:
      - postgres-network

  webapi:
    platform: linux/amd64
    image: nurullo/instagram_clone_api
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    ports:
        - "8085:8083"
    depends_on:
        - db
    environment:
        - ASPNETCORE_ENVIRONMENT=Production
        - ASPNETCORE_URLS=http://+:8083
    networks:
        - postgres-network

networks:
  postgres-network:
    driver: bridge

volumes:
  postgresql-data:
